"""
Django settings for NextTrip project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--i=8ju5ki1&a@1r=!hrxtxi2lolu#1pzayo!i8()gwo_@!6y&i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.vercel.app']


# Application definition

INSTALLED_APPS = [
    #  "admin_interface",
    # "colorfield",
    'loginpage',
    'nextbus',
    'buytickets',
    'reviews',
    'payment',
    # 'admin_material.apps.AdminMaterialDashboardConfig',
    
    # admin pannel jazmin
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',#added white noise for vercel deployment
]

ROOT_URLCONF = 'NextTrip.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'NextTrip.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# ***************
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# *******************


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





# settings.py

PAYPAL_CLIENT_ID = 'AQGvJ_CKEFrsJ0CqRMjPsi4yO9CgpbbRJ153Z8fnbQ8Ahu9LaxD48MInq3ShpiU-brKnS-Qyl1jOat01'
PAYPAL_SECRET_KEY = 'EAFFiBA1HY7-ymFSaEgn2I-DA125a45STD_lzf5JwLwSnWgIFkMJcFJGofZed_3RY4ZbMrJl8WmyQqNQ'




PAYPAL_CLIENT_ID = 'AQGvJ_CKEFrsJ0CqRMjPsi4yO9CgpbbRJ153Z8fnbQ8Ahu9LaxD48MInq3ShpiU-brKnS-Qyl1jOat01'
PAYPAL_SECRET = 'EAFFiBA1HY7-ymFSaEgn2I-DA125a45STD_lzf5JwLwSnWgIFkMJcFJGofZed_3RY4ZbMrJl8WmyQqNQ'



# Jazzmin Admin pannel cutomization
JAZZMIN_SETTINGS = {
'site_header':"NextTrip Dashboard",
'site_brand':"NextTRip Dashboard",
# 'site_logo': "nextbus/NT.png", 
'copyright': "held by Rakshan and Anshu",


}