# Generated by Django 4.2.1 on 2024-03-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
