# Generated by Django 4.2.1 on 2024-02-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('reg_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('cost', models.FloatField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextbus.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('available_seats', models.IntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextbus.route')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('arrival_time', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextbus.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextbus.station')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='end_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_routes', to='nextbus.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_routes', to='nextbus.station'),
        ),
    ]
